const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Camera3D,
		C3.Plugins.Shape3D,
		C3.Behaviors.Sin,
		C3.Plugins.Sprite,
		C3.Plugins.Keyboard,
		C3.Behaviors.Tween,
		C3.Behaviors.Fade,
		C3.Plugins.Spritefont2,
		C3.Plugins.Browser,
		C3.Plugins.Button,
		C3.Plugins.TextBox,
		C3.Plugins.Text,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetZElevation,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Camera3D.Acts.LookAtPosition,
		C3.Plugins.Shape3D.Cnds.OnCreated,
		C3.Plugins.Shape3D.Acts.SetWidth,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Shape3D.Acts.SetTowardPosition,
		C3.Plugins.Camera3D.Exps.CameraX,
		C3.Plugins.Camera3D.Exps.CameraY,
		C3.Plugins.Shape3D.Exps.X,
		C3.Plugins.Shape3D.Exps.Y,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Exps.ZElevation,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.CompareBetween,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Keyboard.Exps.StringFromKeyCode,
		C3.Plugins.Keyboard.Exps.LastKeyCode,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Shape3D.Cnds.CompareInstanceVar,
		C3.Plugins.Shape3D.Acts.SetY,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.Spritefont2.Acts.SetDefaultColor,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.TextBox.Acts.SetText,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Exps.int,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.System.Acts.GoToLayout
	];
};
self.C3_JsPropNameTable = [
	{"3DCamera": 0},
	{AngleOfMotion: 0},
	{Sine: 0},
	{CharacterBillboard: 0},
	{CharacterTextures: 0},
	{Keyboard: 0},
	{Pillar: 0},
	{Wall: 0},
	{Door: 0},
	{編號: 0},
	{門: 0},
	{Ground: 0},
	{Ceiling: 0},
	{CellBarsLeft: 0},
	{CellBarsRight: 0},
	{Tween: 0},
	{Fade: 0},
	{Sprite: 0},
	{朱雀: 0},
	{白虎: 0},
	{玄武: 0},
	{青龍: 0},
	{补间动画: 0},
	{題目: 0},
	{題目來緣: 0},
	{文字2: 0},
	{Room: 0},
	{Seaweed: 0},
	{WallOverlay: 0},
	{WaterBubble: 0},
	{上岸: 0},
	{PlayerGraphics: 0},
	{Browser: 0},
	{密室: 0},
	{沼澤: 0},
	{人數: 0},
	{Text: 0},
	{浮起: 0},
	{失敗: 0},
	{思考秒數: 0},
	{音頻: 0},
	{CenterX: 0},
	{CenterY: 0},
	{階段: 0},
	{題目目數: 0},
	{題目數: 0},
	{CameraAngle: 0},
	{HorizontalCameraDistance: 0},
	{VerticalCameraDistance: 0},
	{Direction: 0},
	{ANGLEOFFSET: 0},
	{CharToCamAngle: 0},
	{FixedCharAngle: 0},
	{VectorMod: 0},
	{FloatAngle: 0},
	{RoundTo: 0},
	{CurrentAngle: 0},
	{DistanceFromCharacter: 0},
	{InitialZ: 0},
	{ZOffset: 0},
	{ColorFrame: 0},
	{活: 0},
	{重製: 0},
	{門1: 0},
	{門2: 0},
	{門3: 0},
	{門4: 0},
	{上去編號: 0},
	{成功時間: 0},
	{死亡時間: 0},
	{時間: 0},
	{思考時間: 0}
];

self.InstanceType = {
	_3DCamera: class extends self.IInstance {},
	CharacterBillboard: class extends self.I3DShapeInstance {},
	CharacterTextures: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Pillar: class extends self.I3DShapeInstance {},
	Wall: class extends self.I3DShapeInstance {},
	Door: class extends self.I3DShapeInstance {},
	門: class extends self.I3DShapeInstance {},
	Ground: class extends self.ISpriteInstance {},
	Ceiling: class extends self.ISpriteInstance {},
	CellBarsLeft: class extends self.ISpriteInstance {},
	CellBarsRight: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	朱雀: class extends self.ISpriteInstance {},
	白虎: class extends self.ISpriteInstance {},
	玄武: class extends self.ISpriteInstance {},
	青龍: class extends self.ISpriteInstance {},
	題目: class extends self.I3DShapeInstance {},
	題目來緣: class extends self.ISpriteInstance {},
	文字2: class extends self.ISpriteFontInstance {},
	Room: class extends self.I3DShapeInstance {},
	Seaweed: class extends self.ISpriteInstance {},
	WallOverlay: class extends self.ISpriteInstance {},
	WaterBubble: class extends self.ISpriteInstance {},
	PlayerGraphics: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	密室: class extends self.IButtonInstance {},
	沼澤: class extends self.IButtonInstance {},
	人數: class extends self.ITextInputInstance {},
	Text: class extends self.ITextInstance {},
	浮起: class extends self.ITextInputInstance {},
	失敗: class extends self.ITextInputInstance {},
	思考秒數: class extends self.ITextInputInstance {},
	音頻: class extends self.IInstance {}
}